[tool.black]
    target-version = ['py38']
    experimental-string-processing = true
    skip-magic-trailing-comma = true

[tool.coverage.run]
    branch = true
    omit = [
        "setup.py",
        "data_browser/migrations/*.py",
    ]

[tool.coverage.report]
    exclude_lines = [
        "assert",
        "pragma: no cover",
        "pragma: postgres",
        "pragma: not postgres",
        "pragma: not sqlite",
        "pragma: mysql",
        "pragma: django < 3.1",
        "pragma: django != 3.1.3",
    ]

[tool.flake8]
    extend-ignore = "E203, E501"

[tool.isort]
    multi_line_output=3
    include_trailing_comma=true
    force_grid_wrap=0
    use_parentheses=true
    line_length=88
    default_section="THIRDPARTY"
    known_first_party="data_browser,tests"

[tool.pytest.ini_options]
    addopts = [
        "-ra",
        "--reuse-db",
        "--durations=20",
        "--cov=data_browser",
        "--cov=tests",
        "--no-cov-on-fail",
        "--cov-fail-under=100",
        "--cov-report=term-missing:skip-covered",
    ]
    norecursedirs = [
        ".*",
        "__pycache__",
        "static",
        "fixtures",
        "templates",
        "migrations",
        "frontend",
        "build",
        "*.egg-info",
        "dist",
        "web_root",
    ]
